name: todo-app
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    # port for redirection : port of our engine x
      - 8000:80
    depends_on:
      - server
      - client
  client:
    image: "node:22"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./client/:/home/node/app
    expose:
      - "5173"
    ports:
    # port it will listen to : port of the actual frontend app
      - "5173:5173"
    command: "npm run dev"
  server:
    image: todo-app/server
    build: ./server
    volumes:
      - ./server/:/usr/src/app
    expose:
      - "4000"
    ports:
    # port listen to : port of our app
      - "8001:4000"
    command: "python src/server.py"
    environment:
      - DEBUG=true
    env_file:
      - path: ./.env
        required: true